BLACK = 0x0000
BLUE = 0x001F
RED = 0xf800
GREEN = 0x07E0
CYAN = 0x07FF
MAGENTA = 0xF81F
YELLOW = 0xFFE0
WHITE = 0xFFFF

# GRAY = 0x7BEF

class ST7789:
    def __init__(self, *args, **kwargs) -> None: ...
    def init(self) -> None: ...
    def fill(self, color: int) -> None: ...
    def pixel(self, x: int, y: int, color: int) -> None: ...

    def text(self, font, text: str,
             x: int, y: int,
             forground_color: int, background_color: int) -> None: ...

    def show(self) -> None: ...
    def scroll(self, dx: int, dy: int) -> None: ...
    def invert(self, invert: bool) -> None: ...
    def contrast(self, contrast: int) -> None: ...
